### ISSUE TITLE
Multi-id / platform query?

### ISSUE THREAD

**Issue by SBS-EREHM** [argovis/demo_notebooks#5]
I have a specific set of floats (wmoIDs) for want for which I want to query and retrieve data.

Is there a way to query for multiple Argo platforms (or ids) in a single avh.query?  I don't see that capability in the argovis API....

Of course, I can write a help function looping around a query for each platform....

Best,

Eric

**Comment by BillMills** [comment]
Hi Eric - thanks for asking. The expectation is that you'd loop over requests, each asking for a single platform. The reason for this is that individual requests need to be circumscribed in size, as opposed to arbitrarily large. I'm going to close this issue, but feel free to post below if you have questions on how to proceed here.

**Comment by BillMills** [comment]
(also if you're asking for a large list of platforms, more than 10, bear in mind the rate limiter will throttle these requests to about 1 / 10s, so if you write a loop, you might need to impose appropriate delays).

**Comment by SBS-EREHM** [comment]
Roger on both counts.  Already wrote the loop, just didn’t know if this was 1-platform/query was a conscious decision - understand it was and why.

Thanks for your comments and the Python interface to the API.

Best,

- eric
***@***.******@***.***>



On May 18, 2023, at 11:55 AM, Bill Mills ***@***.******@***.***>> wrote:

This Message Is From an External Sender
This message came from outside your organization. Use caution when opening.


(also if you're asking for a large list of platforms, more than 10, bear in mind the rate limiter will throttle these requests to about 1 / 10s, so if you write a loop, you might need to impose appropriate delays).

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_argovis_demo-5Fnotebooks_issues_5-23issuecomment-2D1553494718&d=DwMCaQ&c=9mghv0deYPYDGP-W745IEdQLV1kHpn4XJRvR6xMRXtA&r=oyDiokJpqC12t0ZN_mTYGu2t7Pnrk0fjHVsGJ33nKtw&m=2xpTr3Cgb1ZMfvQdXVU2tsrBWECwNZuDdOiN71VspFavOW5DfD2rn39iMmP416Zk&s=swZpR2_C6wYdn7PO2Q2c7gbLdR_zW3k8VbpZI1Ge6xc&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQJ4AMJNS7OK22IJF4YUYO3XGZWDJANCNFSM6AAAAAAYFWUIWQ&d=DwMCaQ&c=9mghv0deYPYDGP-W745IEdQLV1kHpn4XJRvR6xMRXtA&r=oyDiokJpqC12t0ZN_mTYGu2t7Pnrk0fjHVsGJ33nKtw&m=2xpTr3Cgb1ZMfvQdXVU2tsrBWECwNZuDdOiN71VspFavOW5DfD2rn39iMmP416Zk&s=tStg74_e3u5-WASb23wjbe91Bkb09VRIJyddSXd8FXU&e=>.
You are receiving this because you authored the thread.

Please be advised that this email may contain confidential information. If you are not the intended recipient, please notify us by email by replying to the sender and delete this message. The sender disclaims that the content of this email constitutes an offer to enter into, or the acceptance of, any agreement; provided that the foregoing does not invalidate the binding effect of any digital or other electronic reproduction of a manual signature that is included in any attachment.
